nelmio_api_doc:
    documentation:
        servers:
            - url: http://scanpack.local
              description: API over HTTP
            - url: https://scanpack.local
              description: API over HTTPS
        info:
            title: Scanpack
            description: This is an awesome app!
            version: 1.0.0
            x-build: #CommitHash
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                TokenExpirationDate:
                    properties:
                        refresh_token_expiration:
                            title: refresh_token_expiration
                            type: int
                            example: "1714943477"
        security:
            - Bearer: [ ]

        paths:
            /api/login_check:
                post:
                    tags:
                        - Login
                    summary: Login
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        email:
                                            type: string
                                        password:
                                            type: string
                                    type: object
                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            refreshToken:
                                                type: string
                                            refresh_token_expiration:
                                                type: int
                                                example: "1714943477"
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Invalid JSON.
                    security: [ ]
            /api/token/refresh:
                post:
                    tags:
                        - Login
                    summary: Ask to renew valid JWT without asking for user credentials. The token is not changed but the datetime is increased.
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        refreshToken:
                                            type: string
                                    type: object
                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            refreshToken:
                                                type: string
                                            refresh_token_expiration:
                                                type: int
                                                example: "1714943477"
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Invalid JSON.
                    security: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns: # document only routes with a host of the form api.*
            - ^api\.
